### ISSUE TITLE
Missing input file 

### ISSUE THREAD

**Issue by raspberryice** [facebookresearch/wsd-biencoders#1]
Hi,
It seems that this file 'Data_Validation/candidatesWN30.txt' is required for running the code but not including in the repo.

**Comment by blvns** [comment]
If you are trying to run the biencoder.py script, that file expects you to have a copy of the WSD Unified Framework dataset (it can be found [here](http://lcl.uniroma1.it/wsdeval/)), which has the candidatesWN30.txt file. You can then give the path to the dataset's top level directory when running biencoder.py as one of the arguments: "--dataset-path \<filepath\>".  That should allow the script to find all of the WSD data files. 

If that approach doesn't work, please let me know! It'd be helpful in that case if you can include the program you're trying to run, the line(s) where any errors occur, and a copy of any error messages you get so I can replicate the issue.

**Comment by raspberryice** [comment]
Thanks for the reply! I was downloading the training and evaluation files separately but I now see the file in the whole evaluation framework zip file.
