### ISSUE TITLE
ckpt of the bert-base

### ISSUE THREAD

**Issue by henryhuanghenry** [facebookresearch/wsd-biencoders#5]
Hello, 
Thanks for sharing the code and the checkpoints of your model.
Would you mind sharing the ckpt of the baseline models such as the bert-base for research purpose?
I find that you share the codes of training the baselines. Really appreciate it!
I would be grateful if you could also share the ckpt of the baselines for fine-tuning. It would save me a lot of training time.

**Comment by blvns** [comment]
Are you referring to the underlying pretrained models we used to initialize the biencoder? Or the frozen and finetuned baseline models from the paper?

If you mean the checkpoints for the underlying pretrained model we used: they are all available through Huggingface; you can find all of those models [here](https://huggingface.co/models) with documentation on how to use them.

**Comment by henryhuanghenry** [comment]
Thanks for your reply.
I mean the checkpoint of the frozen and finetuned baseline models from the paper.
I would really appreciate that if you could provide some of them.
Thanks a lot!

**Comment by blvns** [comment]
Hi! Sorry for the delay. I still had the BERT baseline models and added them to a separate google drive zip file: https://drive.google.com/file/d/1MXJnefrvEL1Nyvan79dVrq_bZp8d7m-1/view?usp=sharing. Note that the finetuned model is different from the bi-encoder, and I don't think we actually report results in that setting in the paper. Please let me know if you have any other questions!

**Comment by henryhuanghenry** [comment]
Thank you so much!! 

> "Note that the finetuned model is different from the bi-encoder, and I don't think we actually report results in that setting in the paper."


Yes, I understand the difference. I use the provided frozen (lr1e-4, batchsize128) and fine-tune (lr5e-5, batchsize64or128) code to train the Bert-base model and compare the result with the Bert-base model listed in Table 1. And I am struggling to improve my model's performance on the Dev set from 66.2 to 68.6 which is reported on your paper.  I have grid-searched almost all the combinations of the parameters.
Thus, I asked for the ckpt in the previous comment hoping that I could figure out some potential reasons.
And I find that the provided ckpt of the  Bert-base model also achieved 66.2 on the Dev set.
So, would it be possible that the BERT-base baseline in the Table 1 is not referring to the fine-tuned bert-base trained using your codes? Maybe I get it wrong? Or maybe the inconsistency is caused by different settings?
Anyway, thanks for your kindness and reply!
Best wishes.
